# Generated by Django 4.1 on 2022-08-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_alter_sisuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('nb_of_credits', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='availableCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=12)),
                ('instructor', models.CharField(max_length=200)),
                ('registered_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('time', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.courses')),
            ],
        ),
    ]
