# Generated by Django 4.1 on 2022-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_courses_availablecourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecourses',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
