# Generated by Django 4.1 on 2022-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_availablecourses_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecourses',
            name='instructor',
            field=models.CharField(default='Staff', max_length=200),
        ),
    ]
