# Generated by Django 4.1 on 2022-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_alter_availablecourses_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisuser',
            name='admin_allows_registration',
            field=models.BooleanField(default=False),
        ),
    ]
