# Generated by Django 4.1 on 2022-08-29 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_sisuser_is_registered_in_curr_sem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('registered_class_id', models.CharField(max_length=10)),
                ('instructor_id', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=20)),
                ('grade', models.FloatField(default='TBA', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
            ],
        ),
        migrations.AddField(
            model_name='availablecourses',
            name='room',
            field=models.CharField(default='TBA', max_length=20),
        ),
    ]
