# Generated by Django 4.1 on 2022-08-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_registeredcourses_availablecourses_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredcourses',
            old_name='instructor_id',
            new_name='instructor_name',
        ),
    ]
