# Generated by Django 4.1 on 2022-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_alter_registeredcourses_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sisuser',
            old_name='isAdmin',
            new_name='is_instructor',
        ),
        migrations.AddField(
            model_name='sisuser',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
