# Generated by Django 4.1 on 2022-08-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_rename_isadmin_sisuser_is_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sisuser',
            name='is_instructor',
        ),
    ]
