# Generated by Django 4.1 on 2022-08-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_remove_sisuser_is_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcourses',
            name='instructor_name',
            field=models.CharField(max_length=200),
        ),
    ]
